name: galli_vector_plugin
description: A Galli vector map widget that displays a map with custom markers, lines, circles and polygons.
version: 0.2.1
homepage: https://gallimaps.com

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  meta: ^1.0.5
  flutter_cube: ^0.1.1
  http:
  geolocator: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

plugin:
  platforms:
    android:
      package: map.galliexpress.galli_vector_plugin
      pluginClass: GalliVectorPlugin
    ios:
      pluginClass: GalliVectorPlugin
